/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov <gennady.pospelov@gmail.com>
 *
 *****************************************************************************/

#ifndef FOLDERBASEDTEST_H
#define FOLDERBASEDTEST_H

#include <gtest/gtest.h>

#include <string>

//! Convenience class which creates a directory on disk for test content.

class FolderBasedTest : public ::testing::Test
{
public:
  FolderBasedTest(std::string folder_name);
  ~FolderBasedTest();

  std::string GetTestDirectory() const;

  std::string GetFilePath(const std::string& file_name) const;

protected:
  std::string m_folder_name;  //! The name of the folder for files generated by this test.
};

#endif  //  FOLDERBASEDTEST_H
