name: sup-config
buildsystem: cmake
config-opts:
  - -DCOA_BUILD_TESTS=OFF
sources:
  - type: git
    url: ssh://git@git.iter.org/coa/sup-config.git
    tag: v1.3
modules:
  - ../sup-protocol/org.iter.sup-protocol.yml
  - ../sup-utils/org.iter.sup-utils.yml
