# Project main configuration

include(CTest)
include(CodeTools)
include(GNUInstallDirs)
include(FindPackageMessage)
include(COASetupCodacEnvironment)
include(COASetupQt)

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------
get_filename_component(SEQUENCERGUI_PROJECT_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

set(SEQUENCERGUI_SOVERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR})
set(SEQUENCERGUI_BUILDVERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
set(SEQUENCERGUI_TESTRESULT_DIR ${CMAKE_BINARY_DIR}/test_result)

# -----------------------------------------------------------------------------
# Directories
# -----------------------------------------------------------------------------
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})

file(MAKE_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
file(MAKE_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
file(MAKE_DIRECTORY ${SEQUENCERGUI_TESTRESULT_DIR})

if (DEFINED TEST_OUTPUT_DIRECTORY)
  file(MAKE_DIRECTORY ${TEST_OUTPUT_DIRECTORY})
else()
  set(TEST_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
endif()

# directory for autogenerated configs
set(SEQUENCERGUI_AUTOGEN_DIR ${CMAKE_BINARY_DIR}/autogen/sequencergui)
file(MAKE_DIRECTORY ${SEQUENCERGUI_AUTOGEN_DIR})

# -----------------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------------
find_package(Threads)
find_package(sup-gui-core REQUIRED)
find_package(sequencer REQUIRED)
find_package(sup-auto-server REQUIRED)
find_package(sup-epics REQUIRED)

# -----------------------------------------------------------------------------
# Generating config files
# -----------------------------------------------------------------------------
configure_file(${SEQUENCERGUI_PROJECT_DIR}/cmake/configs/testconfig.h.in  ${SEQUENCERGUI_AUTOGEN_DIR}/testconfig.h @ONLY)
configure_file(${SEQUENCERGUI_PROJECT_DIR}/cmake/configs/version_constants.h.in  ${SEQUENCERGUI_AUTOGEN_DIR}/version_constants.h @ONLY)
