# Project main configuration

include(COACommonConfig)
include(COASetupCodacEnvironment)
include(COASetupQt)
include(CodeTools)
include(GenerateExportHeader)

# -----------------------------------------------------------------------------
# Directories
# -----------------------------------------------------------------------------
# directory for tests that produce output
set(SEQUENCERGUI_TESTRESULT_DIR ${CMAKE_CURRENT_BINARY_DIR}/test_result)
file(MAKE_DIRECTORY ${SEQUENCERGUI_TESTRESULT_DIR})

# directory for autogenerated configs
set(SEQUENCERGUI_AUTOGEN_DIR ${CMAKE_CURRENT_BINARY_DIR}/autogen/oac_tree_gui)
file(MAKE_DIRECTORY ${SEQUENCERGUI_AUTOGEN_DIR})

# runtime directory to build application
set(SEQUENCERGUI_APP_RUNTIME_DIR ${CMAKE_CURRENT_BINARY_DIR}/bin)
file(MAKE_DIRECTORY ${SEQUENCERGUI_APP_RUNTIME_DIR})

# -----------------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------------
include(FetchGithubDeps)
find_package(Threads)
find_package(sup-gui-core REQUIRED)
find_package(oac-tree REQUIRED)
find_package(oac-tree-server REQUIRED)
find_package(sup-epics REQUIRED)

# -----------------------------------------------------------------------------
# Generating config files
# -----------------------------------------------------------------------------
get_filename_component(SEQUENCERGUI_PROJECT_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
configure_file(${SEQUENCERGUI_PROJECT_DIR}/cmake/configs/testconfig.h.in  ${SEQUENCERGUI_AUTOGEN_DIR}/testconfig.h @ONLY)
configure_file(${SEQUENCERGUI_PROJECT_DIR}/cmake/configs/version_constants.h.in  ${SEQUENCERGUI_AUTOGEN_DIR}/version_constants.h @ONLY)

# -----------------------------------------------------------------------------
# Compiler options
# -----------------------------------------------------------------------------
if (COA_COVERAGE)
  message(STATUS "Enabling test coverage information")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -g -fno-inline --coverage")
endif()
